import { Router } from 'express';
import { authMiddleware } from '../middleware/auth.js';
import { tenantMiddleware } from '../middleware/tenant.js';
import authRoutes from './auth.js';
import agentsRoutes from './agents.js';
import tasksRoutes from './tasks.js';
import activityRoutes from './activity.js';
import standupsRoutes from './standups.js';
import configRoutes from './config.js';
import cronJobsRoutes from './cronJobs.js';
import notificationsRoutes from './notifications.js';
import deliverablesRoutes from './deliverables.js';
import webhookRoutes from './webhooks.js';
import telegramRoutes from './telegram.js';
import setupRoutes from './setup.js';
import settingsRoutes from './settings.js';
import memoryGraphRoutes from './memoryGraph.js';
import documentsRoutes from './documents.js';
import squadChatRoutes from './squadChat.js';
import machinesRoutes from './machines.js';
import whatsappRoutes, { whatsappWebhookRouter } from './whatsapp.js';
import approvalsRoutes from './approvals.js';
import boardGroupsRoutes from './boardGroups.js';
import tagsRoutes from './tags.js';
import apiTokensRoutes from './apiTokens.js';
import billingRoutes from './billing.js';
import adminRoutes from './admin.js';
import systemRoutes from './system.js';
import sessionsRoutes from './sessions.js';
import weatherRoutes from './weather.js';
import healthRoutes from './health.js';
import marketplaceRoutes from './marketplace.js';

const router = Router();

router.use('/auth', authRoutes);

router.use('/v1/whatsapp', whatsappWebhookRouter);

router.use('/health', healthRoutes);
router.use('/v1/health', healthRoutes);
router.use('/v1/weather', authMiddleware, tenantMiddleware, weatherRoutes);
router.use('/v1/system', authMiddleware, tenantMiddleware, systemRoutes);
router.use('/v1/sessions', authMiddleware, tenantMiddleware, sessionsRoutes);
router.use('/v1/agents', authMiddleware, tenantMiddleware, agentsRoutes);
router.use('/v1/tasks', authMiddleware, tenantMiddleware, tasksRoutes);
router.use('/v1/activity', authMiddleware, tenantMiddleware, activityRoutes);
router.use('/v1/standups', authMiddleware, tenantMiddleware, standupsRoutes);
router.use('/v1/config', authMiddleware, tenantMiddleware, configRoutes);
router.use('/v1/cron-jobs', authMiddleware, tenantMiddleware, cronJobsRoutes);
router.use('/v1/notifications', authMiddleware, tenantMiddleware, notificationsRoutes);
router.use('/v1/deliverables', authMiddleware, tenantMiddleware, deliverablesRoutes);
router.use('/v1/webhooks', authMiddleware, tenantMiddleware, webhookRoutes);
router.use('/v1/telegram', authMiddleware, tenantMiddleware, telegramRoutes);
router.use('/v1/setup', authMiddleware, tenantMiddleware, setupRoutes);
router.use('/v1/settings', authMiddleware, tenantMiddleware, settingsRoutes);
router.use('/v1/documents', authMiddleware, tenantMiddleware, documentsRoutes);
router.use('/v1/memory-graph', authMiddleware, tenantMiddleware, memoryGraphRoutes);
router.use('/v1/squad-chat', authMiddleware, tenantMiddleware, squadChatRoutes);
router.use('/v1/machines', authMiddleware, tenantMiddleware, machinesRoutes);
router.use('/v1/whatsapp', authMiddleware, tenantMiddleware, whatsappRoutes);
router.use('/v1/approvals', authMiddleware, tenantMiddleware, approvalsRoutes);
router.use('/v1/board-groups', authMiddleware, tenantMiddleware, boardGroupsRoutes);
router.use('/v1/tags', authMiddleware, tenantMiddleware, tagsRoutes);
router.use('/v1/api-tokens', authMiddleware, tenantMiddleware, apiTokensRoutes);
router.use('/v1/billing', billingRoutes);
router.use('/v1/marketplace', authMiddleware, tenantMiddleware, marketplaceRoutes);
router.use('/admin/v1', adminRoutes);

export default router;
