import { NextResponse } from 'next/server';
import { setSetupConfig, isSetupComplete, getSetupConfig } from '@/lib/local-db';
import { reinitializeHubSync } from '@/lib/hub-sync';
import { validateAuthToken } from '@/lib/auth';
import { cookies } from 'next/headers';
import fs from 'fs';
import path from 'path';
import os from 'os';

function sanitizeEnvValue(val: string): string {
  return val.replace(/[\r\n]/g, '').trim();
}

interface SetupData {
  standalone: boolean;
  hubUrl?: string;
  hubApiKey?: string;
  nodeId?: string;
  adminPassword: string;
  nodeName: string;
  nodeDescription?: string;
  llmProvider?: string;
  openaiKey?: string;
  anthropicKey?: string;
  ollamaUrl?: string;
  telegramToken?: string;
  discordWebhook?: string;
}

export async function POST(req: Request) {
  try {
    const alreadyComplete = isSetupComplete();
    const forceRerun = getSetupConfig('setup_force_rerun') === 'true';
    if (alreadyComplete && !forceRerun) {
      const cookieStore = cookies();
      const authCookie = cookieStore.get('node_auth');
      if (!authCookie?.value || !validateAuthToken(authCookie.value)) {
        return NextResponse.json({ success: false, error: 'Unauthorized' }, { status: 401 });
      }
    }

    const data: SetupData = await req.json();

    if (!data.adminPassword || data.adminPassword.length < 6) {
      return NextResponse.json({ success: false, error: 'Password must be at least 6 characters' }, { status: 400 });
    }
    if (!data.nodeName || !data.nodeName.trim()) {
      return NextResponse.json({ success: false, error: 'Node name is required' }, { status: 400 });
    }
    if (!data.standalone) {
      if (!data.hubUrl || !data.hubApiKey || !data.nodeId) {
        return NextResponse.json({ success: false, error: 'Hub URL, API Key, and Node ID are required when not in standalone mode' }, { status: 400 });
      }
    }

    setSetupConfig('standalone', data.standalone ? 'true' : 'false');
    setSetupConfig('node_name', sanitizeEnvValue(data.nodeName));
    if (data.nodeDescription) setSetupConfig('node_description', sanitizeEnvValue(data.nodeDescription));
    if (data.llmProvider) setSetupConfig('llm_provider', sanitizeEnvValue(data.llmProvider));
    if (data.ollamaUrl) setSetupConfig('ollama_url', sanitizeEnvValue(data.ollamaUrl));

    const envLines: string[] = [
      '# SquidJob Node Configuration',
      `# Generated by Setup Wizard: ${new Date().toISOString()}`,
      '',
      `ADMIN_PASSWORD=${sanitizeEnvValue(data.adminPassword)}`,
      `NODE_NAME=${sanitizeEnvValue(data.nodeName)}`,
    ];

    if (data.standalone) {
      envLines.push('', '# Standalone mode (no Hub connection)');
      envLines.push('__SETUP_STANDALONE=true');
    } else if (data.hubUrl) {
      envLines.push('', '# Hub connection');
      envLines.push(`NODE_HUB_URL=${sanitizeEnvValue(data.hubUrl)}`);
      if (data.hubApiKey) envLines.push(`NODE_HUB_API_KEY=${sanitizeEnvValue(data.hubApiKey)}`);
      if (data.nodeId) envLines.push(`NODE_ID=${sanitizeEnvValue(data.nodeId)}`);
    }

    if (data.openaiKey) {
      envLines.push('', '# LLM API');
      envLines.push(`OPENAI_API_KEY=${sanitizeEnvValue(data.openaiKey)}`);
    }
    if (data.anthropicKey) {
      if (!data.openaiKey) envLines.push('', '# LLM API');
      envLines.push(`ANTHROPIC_API_KEY=${sanitizeEnvValue(data.anthropicKey)}`);
    }
    if (data.ollamaUrl) {
      if (!data.openaiKey && !data.anthropicKey) envLines.push('', '# LLM API');
      envLines.push(`OLLAMA_URL=${sanitizeEnvValue(data.ollamaUrl)}`);
    }

    if (data.telegramToken) {
      envLines.push('', '# Messaging');
      envLines.push(`TELEGRAM_BOT_TOKEN=${sanitizeEnvValue(data.telegramToken)}`);
    }
    if (data.discordWebhook) {
      if (!data.telegramToken) envLines.push('', '# Messaging');
      envLines.push(`DISCORD_WEBHOOK_URL=${sanitizeEnvValue(data.discordWebhook)}`);
    }

    const openclawDir = process.env.OPENCLAW_DIR || path.join(os.homedir(), '.openclaw');
    envLines.push('', `OPENCLAW_DIR=${openclawDir}`);
    envLines.push('');

    const nodeDir = path.resolve(process.cwd());
    const envPath = path.join(nodeDir, '.env');

    fs.writeFileSync(envPath, envLines.join('\n'), { mode: 0o600 });

    process.env.ADMIN_PASSWORD = sanitizeEnvValue(data.adminPassword);
    process.env.NODE_NAME = sanitizeEnvValue(data.nodeName);
    if (data.standalone) {
      process.env.__SETUP_STANDALONE = 'true';
    } else {
      process.env.__SETUP_STANDALONE = '';
    }
    if (!data.standalone && data.hubUrl) {
      process.env.NODE_HUB_URL = sanitizeEnvValue(data.hubUrl);
      if (data.hubApiKey) process.env.NODE_HUB_API_KEY = sanitizeEnvValue(data.hubApiKey);
      if (data.nodeId) process.env.NODE_ID = sanitizeEnvValue(data.nodeId);
    }
    if (data.openaiKey) process.env.OPENAI_API_KEY = sanitizeEnvValue(data.openaiKey);
    if (data.anthropicKey) process.env.ANTHROPIC_API_KEY = sanitizeEnvValue(data.anthropicKey);
    if (data.ollamaUrl) process.env.OLLAMA_URL = sanitizeEnvValue(data.ollamaUrl);
    if (data.telegramToken) process.env.TELEGRAM_BOT_TOKEN = sanitizeEnvValue(data.telegramToken);
    if (data.discordWebhook) process.env.DISCORD_WEBHOOK_URL = sanitizeEnvValue(data.discordWebhook);

    setSetupConfig('setup_complete', 'true');
    setSetupConfig('setup_force_rerun', 'false');

    if (!data.standalone) {
      try { reinitializeHubSync(); } catch (e) {
        console.log('[Setup] Hub sync reinit deferred:', e);
      }
    }

    const response = NextResponse.json({ success: true });
    response.cookies.set('setup_complete', 'true', {
      httpOnly: true,
      path: '/',
      maxAge: 60 * 60 * 24 * 365,
      sameSite: 'lax',
    });
    return response;
  } catch (err: unknown) {
    console.error('[Setup] Save failed:', err);
    const message = err instanceof Error ? err.message : 'Failed to save configuration';
    return NextResponse.json({ success: false, error: message }, { status: 500 });
  }
}
